# Generated by Django 4.1 on 2023-09-26 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], default=False, max_length=1, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.SmallIntegerField(default=False, verbose_name='рост'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purpose_of_training',
            field=models.CharField(choices=[('weight_loss', 'похудение'), ('relief', 'рельеф тела'), ('muscle_mass', 'набор мышечной массы'), ('endurance', 'выносливость')], default=False, max_length=12, verbose_name='цель программы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='training_level',
            field=models.CharField(choices=[('beginner', 'новичок'), ('amateur', 'любитель'), ('pro', 'профессионал')], default=False, max_length=8, verbose_name='уровень пользователя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.SmallIntegerField(default=False, verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=False, verbose_name='возраст'),
        ),
    ]
