# Generated by Django 4.2.4 on 2023-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], default=False, max_length=12, verbose_name='пол'),
        ),
    ]
