version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - appdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: movies
    ports:
      - "5433:5432"
  trainer_api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/.:/code/backend
    ports:
      - "8000:8000"
  trainer_front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "10001:10001"
    depends_on:
      - trainer_api
volumes:
  appdata: