version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - appdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: movies
    ports:
      - "5433:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  trainer_api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn backend.wsgi:application -c config/gunicorn.conf.py"
    depends_on:
      - db
    volumes:
      - ./backend/.:/code/backend
      - /var/www/static/back:/var/www/static/back
    ports:
      - "8000:8000"
  celery:
    build: .
    command: bash -c "sleep 10 && celery -A backend worker --loglevel=info"
    volumes:
      - ./backend:/code/backend
    depends_on:
      - redis
      - trainer_api
  trainer_front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "10001:10001"
    depends_on:
      - trainer_api
#  trainer_front:
#    build: ./frontend
#    ports:
#      - "10001:10001"
#    depends_on:
#      - trainer_api
volumes:
  appdata: