services:
  - type: web
    name: django
    rootDir: backend
    runtime: python
    buildCommand: 'pip install -r requirements3.txt && python manage.py makemigrations && python manage.py migrate'
    startCommand: python manage.py runserver
    buildFilter:
      paths:
        - backend

databases:
  - name: postgres
    databaseName: movies
    user: movies
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere