# Generated by Django 4.2.4 on 2023-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=200, verbose_name='источник'),
        ),
    ]
