# Generated by Django 4.2.4 on 2023-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='added_by',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(default=2, verbose_name='краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
