# Generated by Django 4.1 on 2023-09-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('meta', models.CharField(max_length=255, verbose_name='мета описание')),
                ('text', models.TextField(verbose_name='текст')),
                ('source', models.CharField(max_length=100, verbose_name='источник')),
                ('is_draft', models.BooleanField(default=True, verbose_name='черновик')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('updated_at', models.DateTimeField(verbose_name='последнее обновление')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True, verbose_name='текущая')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('updated_at', models.DateTimeField(verbose_name='последнее обновление')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программы',
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('updated_at', models.DateTimeField(verbose_name='последнее обновление')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'тренировка',
                'verbose_name_plural': 'тренировки',
                'db_table': 'training_days',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
                ('gender', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='пол')),
                ('age', models.SmallIntegerField(verbose_name='возраст')),
                ('weight', models.SmallIntegerField(verbose_name='вес')),
                ('height', models.SmallIntegerField(verbose_name='рост')),
                ('training_level', models.CharField(choices=[('beginner', 'новичок'), ('amateur', 'любитель'), ('pro', 'профессионал')], max_length=8, verbose_name='уровень пользователя')),
                ('purpose_of_training', models.CharField(choices=[('weight_loss', 'похудение'), ('relief', 'рельеф тела'), ('muscle_mass', 'набор мышечной массы'), ('endurance', 'выносливость')], max_length=12, verbose_name='цель программы')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('updated_at', models.DateTimeField(verbose_name='последнее обновление')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название упражнения')),
                ('description', models.TextField(verbose_name='описание')),
                ('approach_nums', models.SmallIntegerField(verbose_name='количество подходов')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('updated_at', models.DateTimeField(verbose_name='последнее обновление')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainingday', verbose_name='тренировка')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
                'db_table': 'workouts',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='количество повторений')),
                ('result', models.IntegerField(verbose_name='результат')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('updated_at', models.DateTimeField(verbose_name='последнее обновление')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workout', verbose_name='упражнение')),
            ],
            options={
                'verbose_name': 'подход',
                'verbose_name_plural': 'подходы',
                'db_table': 'approaches',
            },
        ),
    ]
